### ISSUE TITLE
What plugin do you use to get the file path at the top of each file?

### ISSUE THREAD

**Issue by Yttrium-32** [dylanfierro/nvim-windows#6]
Hi! I really like you config. I randomly found it while browsing reddit.
I was just wondering what plugin you use to get that file path at the top in open files?
![File_path](https://github.com/TroubleC0re/nvim/assets/102477902/adaf1d97-e4a6-4be5-af02-ae5945f1449f)

**Comment by Darkothh** [comment]
Hi! I use this plugin [nvim-navic](https://github.com/SmiteshP/nvim-navic)

**Comment by Yttrium-32** [comment]
Gotcha, thank you!
