### ISSUE TITLE
Expand tab doesn't work

### ISSUE THREAD

**Issue by Yttrium-32** [dylanfierro/nvim-windows#7]
The expand tab option is set incorrectly.
https://github.com/TroubleC0re/nvim/blob/f468be1f6651440ced69edd02f8ed457fc64e19b/plugin/options.lua#L13

The `expandtab` option is local to each buffer and thus must be set with `vim.bo` instead of `vim.opt`

**Comment by Darkothh** [comment]
When I go back home I will fix it, thank you!

**Comment by Yttrium-32** [comment]
No problem! If you would like you could simply merge my pull request to make those changes.

**Comment by Darkothh** [comment]
Thanks!
